# Site settings
title: A127
description: Apigee-127 website
baseurl: "/site"
url: "http://apigee-127.github.io"
twitter_username: apigee
github_username:  apigee-127

highlighter: pygments
pygments: true

include:
  - _pages
  - _quick_start

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  use_coderay: true

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
