# Site settings
title: A127
description: Apigee-127 website
baseurl: ""
url: "www.a127.io"
twitter_username: apigee
github_username:  apigee-127

include:
  - _pages
  - _quick_start

# Build settings
markdown: kramdown
